theme: jekyll-theme-minimal

title: [Coronavirus en Chile]
description: [Cual es la situación de Chile frente al coronavirus. Algunos graficos para comparar Chile con otros paises del mundo.]

logo: [https://s1.qwant.com/thumbr/0x380/3/6/cf3243090dec69a716b600980297435f902ea2555f271d64f96a75a8138d33/RTS301GM-1024x576.jpg?u=https%3A%2F%2Fd3i6fh83elv35t.cloudfront.net%2Fstatic%2F2020%2F01%2FRTS301GM-1024x576.jpg&q=0&b=1&p=0&a=1]
show_downloads: ["false"]
